baseURL = "https://xuantianctf.github.io/"
title = "Xuantian CTF"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

[outputs]
home = ["HTML", "RSS", "JSON"]
