# Hugo Configuration
title: '玄天 CTF 实验室'
baseURL: 'https://xuantianctf.github.io/'
defaultContentLanguage: en
hasCJKLanguage: true

cascade:
  - target:
      path: /docs/**
    editable: true
    show_breadcrumb: true
    show_date: false
    show_date_updated: true
  - target:
      path: /blog/**
    pager: true
    editable: true
    show_date: true
    show_date_updated: true
    reading_time: true
    show_breadcrumb: false

build:
  writeStats: true
enableGitInfo: true
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
enableInlineShortcodes: true
disableAliases: true
outputs:
  home: [HTML, RSS, WebAppManifest, headers, redirects, backlinks]
  page: [HTML]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
