# Menus Configuration

main:
  - name: "Blog"
    url: "/blog/"
    weight: 20
  - name: "Docs"
    url: "/docs/"
    weight: 30
  - name: "GitHub"
    url: "https://github.com/XuantianCTF"
    weight: 40
